int a;
// printf("10-99 gacha hohlagan soningizni kiriting:");
// scanf("%d", &a);
// if(a==10){
//     puts("O'n");
// }
// else if(a==11){
//     puts("O'n bir");
// }
// else if(a==12){
//     puts("O'n ikki");
// }else if(a==13){
//     puts("O'n uch");
// }else if(a==14){
//     puts("O'n to'rt");
// }else if(a==15){
//     puts("O'n besh");
// }else if(a==16){
//     puts("O'n olti");
// }else if(a==17){
//     puts("O'n yetti");
// }else if(a==18){
//     puts("O'n sakkiz");
// }else if(a==19){
//     puts("O'n to'qqiz");
// }else if(a==20){
//     puts("Yigirma");
// }else if(a==21){
//     puts("Yigirma bir");
// }else if(a==22){
//     puts("Yigirma ikki");
// }else if(a==23){
//     puts("Yigirma uch");
// }else if(a==24){
//     puts("Yigirma to'rt");
// }else if(a==25){
//     puts("Yigirma besh");
// }else if(a==26){
//     puts("Yigirma olti");
// }else if(a==27){
//     puts("Yigirma yetti");
// }else if(a==28){
//     puts("Yigirma sakkiz");
// }else if(a==29){
//     puts("Yigirma to'qqiz");
// }else if(a==30){
//     puts("O'ttiz");
// }else if(a==31){
//     puts("O'ttiz bir");
// }else if(a==32){
//     puts("O'ttiz ikki");
// }else if(a==33){
//     puts("O'ttiz uch");
// }else if(a==34){
//     puts("O'ttiz to'rt");
// }else if(a==35){
//     puts("O'ttiz besh");
// }else if(a==36){
//     puts("O'ttiz olti");
// }else if(a==37){
//     puts("O'ttiz yetti");
// }else if(a==38){
//     puts("O'ttiz sakkiz");
// }else if(a==39){
//     puts("O'ttiz to'qqiz");
// }else if(a==40){
//     puts("Qirq");
// }else if(a==41){
//     puts("Qirq bir");
// }else if(a==42){
//     puts("Qirq ikki");
// }else if(a==43){
//     puts("Qirq uch");
// }else if(a==44){
//     puts("Qirq to'rt");
// }else if(a==45){
//     puts("Qirq besh");
// }else if(a==46){
//     puts("Qirq olti");
// }else if(a==47){
//     puts("Qirq yetti");
// }else if(a==48){
//     puts("Qirq sakkiz");
// }else if(a==49){
//     puts("Qirq to'qqiz");
// }else if(a==50){
//     puts("Ellik");
// }else if(a==51){
//     puts("Ellik bir");
// }else if(a==52){
//     puts("Ellik ikki");
// }else if(a==53){
//     puts("Ellik uch");
// }else if(a==54){
//     puts("Ellik to'rt");
// }else if(a==55){
//     puts("Ellik besh");
// }else if(a==56){
//     puts("Ellik olti");
// }else if(a==57){
//     puts("Ellik yetti");
// }else if(a==58){
//     puts("Ellik sakkiz");
// }else if(a==59){
//     puts("Ellik to'qqiz");
// }else if(a==60){
//     puts("Oltmish");
// }else if(a==61){
//     puts("Oltmish bir");
// }else if(a==62){
//     puts("Oltmish ikki");
// }else if(a==63){
//     puts("Oltmish uch");
// }else if(a==64){
//     puts("Oltmish to'rt");
// }else if(a==65){
//     puts("Oltmish besh");
// }else if(a==66){
//     puts("Oltmish olti");
// }else if(a==67){
//     puts("Oltmish yetti");
// }else if(a==68){
//     puts("Oltmish sakkiz");
// }else if(a==69){
//     puts("Oltmish to'qqiz");
// }else if(a==70){
//     puts("Yetmish");
// }else if(a==71){
//     puts("Yetmish bir");
// }else if(a==72){
//     puts("Yetmish ikki");
// }else if(a==73){
//     puts("Yetmish uch");
// }else if(a==74){
//     puts("Yetmish to'rt");
// }else if(a==75){
//     puts("Yetmish besh");
// }else if(a==76){
//     puts("Yetmish olti");
// }else if(a==77){
//     puts("Yetmish yetti");
// }else if(a==78){
//     puts("Yetmish sakkiz");
// }else if(a==79){
//     puts("Yetmish to'qqiz");
// }else if(a==80){
//     puts("Sakson");
// }else if(a==81){
//     puts("Sakson bir");
// }else if(a==82){
//     puts("Sakson ikki");
// }else if(a==83){
//     puts("Sakson uch");
// }else if(a==84){
//     puts("Sakson to'rt");
// }else if(a==85){
//     puts("Sakson besh");
// }else if(a==86){
//     puts("Sakson olti");
// }else if(a==87){
//     puts("Sakson yetti");
// }else if(a==88){
//     puts("Sakson sakkiz");
// }else if(a==89){
//     puts("Sakson to'qqiz");
// }else if(a==90){
//     puts("To'qson");
// }else if(a==91){
//     puts("To'qson bir");
// }else if(a==92){
//     puts("To'qson ikki");
// }else if(a==93){
//     puts("To'qson uch");
// }else if(a==94){
//     puts("To'qson to'rt");
// }else if(a==95){
//     puts("To'qson besh");
// }else if(a==96){
//     puts("To'qson olti");
// }else if(a==97){
//     puts("To'qson yetti");
// }else if(a==98){
//     puts("To'qson sakkiz");
// }else{
//     puts("To'qson to'qqiz");
// }